"""Adds repositories/archives."""

########################################################################
# DO NOT EDIT THIS FILE unless you are inside the
# https://github.com/3rdparty/bazel-rules-backward-cpp repository. If you
# encounter it anywhere else it is because it has been copied there in
# order to simplify adding transitive dependencies. If you want a
# different version of bazel-rules-backward-cpp follow the Bazel build
# instructions at https://github.com/3rdparty/bazel-rules-backward-cpp.
########################################################################

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository", "new_git_repository")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

def repos(external = True, repo_mapping = {}):
    maybe(
        git_repository,
        name = "com_github_3rdparty_bazel_rules_backward_cpp",
        remote = "https://github.com/3rdparty/bazel-rules-backward-cpp",
        commit = "69449957a41619e9b8b8be2e9bfaca2ac0642760",
        shallow_since = "1658132015 +0300",
        repo_mapping = repo_mapping,
    )

    maybe(
        new_git_repository,
        name = "com_github_3rdparty_bazel_rules_backward_cpp_stacktrace",
        remote = "https://github.com/3rdparty/bazel-rules-backward-cpp",
        build_file = "@com_github_3rdparty_bazel_rules_backward_cpp//:BUILD.backward-stacktrace.bazel",
        commit = "69449957a41619e9b8b8be2e9bfaca2ac0642760",
        shallow_since = "1658132015 +0300",
    )

    maybe(
        http_archive,
        name = "rules_foreign_cc",
        url = "https://github.com/bazelbuild/rules_foreign_cc/archive/refs/tags/0.9.0.tar.gz",
        sha256 = "2a4d07cd64b0719b39a7c12218a3e507672b82a97b98c6a89d38565894cf7c51",
        strip_prefix = "rules_foreign_cc-0.9.0",
        repo_mapping = repo_mapping,
    )
