"""Adds repositories/archives."""

########################################################################
# DO NOT EDIT THIS FILE unless you are inside the
# https://github.com/3rdparty/bazel-rules-backward-cpp repository. If you
# encounter it anywhere else it is because it has been copied there in
# order to simplify adding transitive dependencies. If you want a
# different version of bazel-rules-backward-cpp follow the Bazel build
# instructions at https://github.com/3rdparty/bazel-rules-backward-cpp.
########################################################################

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository", "new_git_repository")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

def repos(external = True, repo_mapping = {}):
    maybe(
        git_repository,
        name = "com_github_3rdparty_bazel_rules_backward_cpp",
        remote = "https://github.com/3rdparty/bazel-rules-backward-cpp",
        commit = "6a88dc2d7a3ab98514997a4dfaf949f33da72bed",
        shallow_since = "1657095319 +0300",
        repo_mapping = repo_mapping,
    )

    maybe(
        new_git_repository,
        name = "com_github_3rdparty_bazel_rules_backward_cpp_stacktrace",
        remote = "https://github.com/3rdparty/bazel-rules-backward-cpp",
        build_file = "@com_github_3rdparty_bazel_rules_backward_cpp//:BUILD.backward-stacktrace.bazel",
        commit = "87b7682ce4b1c849504e2b3641cebaad62aaef87",
        shallow_since = "1658064115 +0300",
    )
